# -*- coding: utf-8 -*-
"""Modelo_IA_ATMOS_organizado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOn6swBOqsE1H6dSCu6o_30FA00XB-hF

# ATMOS: Sistema Inteligente de Gestión de AC

Notebook organizado para el prototipo ATMOS. El flujo está separado por etapas: generación de datos, entrenamiento, evaluación, funciones operativas, detección de fallas, demostraciones e impacto económico.

> Nota: se reorganizó la estructura y los títulos para mejorar la lectura. La lógica de las celdas de código se conserva.

## 1. Generación de Datos Sintéticos Base y Función de Decisión ATMOS

En esta sección se crean los datos base simulados y la función `decidir()`, que genera las etiquetas que aprende el modelo.
"""

import pandas as pd
import numpy as np

np.random.seed(42)
n = 500

presencia = np.random.randint(0, 2, n)
temp_ambiente = np.random.uniform(22, 35, n)
temp_ac = np.random.uniform(16, 26, n)
delta_t = temp_ambiente - temp_ac
humedad = np.random.uniform(50, 90, n)

df = pd.DataFrame({
    'presencia': presencia,
    'temp_ambiente': temp_ambiente,
    'temp_ac': temp_ac,
    'delta_t': delta_t,
    'humedad': humedad
})

import pandas as pd
import numpy as np

np.random.seed(42)
n = 500

presencia = np.random.randint(0, 2, n)
temp_ambiente = np.random.uniform(22, 35, n)
temp_ac = np.random.uniform(16, 26, n)
delta_t = temp_ambiente - temp_ac
humedad = np.random.uniform(50, 90, n)

df = pd.DataFrame({
    'presencia': presencia,
    'temp_ambiente': temp_ambiente,
    'temp_ac': temp_ac,
    'delta_t': delta_t,
    'humedad': humedad
})

# PARÁMETROS DE DECISIÓN ATMOS

LIMITE_CALOR_MODERADO = 28
LIMITE_CALOR_FUERTE = 30
LIMITE_HUMEDAD_ALTA = 70
DELTA_MINIMO_ESPERADO = 6
TEMP_AC_POCO_FRIA = 22

# FUNCIÓN DE DECISIÓN MEJORADA

def decidir(row):
    # 1. Si no hay personas, se recomienda apagar
    if row['presencia'] == 0:
        return 'apagar'

    # 2. Si hay presencia y el salón está demasiado caliente,
    # se recomienda enfriar fuerte directamente
    if row['temp_ambiente'] >= LIMITE_CALOR_FUERTE:
        return 'enfriar_fuerte'

    # 3. Si hay presencia y calor moderado, no basta con una sola señal.
    # Se cuentan señales adicionales para evitar enfriar fuerte innecesariamente.
    if row['temp_ambiente'] >= LIMITE_CALOR_MODERADO:

        señales_calor = 0

        # Señal 1: humedad alta
        if row['humedad'] >= LIMITE_HUMEDAD_ALTA:
            señales_calor += 1

        # Señal 2: poca diferencia entre temperatura ambiente y temperatura del AC
        if row['delta_t'] < DELTA_MINIMO_ESPERADO:
            señales_calor += 1

        # Señal 3: el aire del AC no está saliendo suficientemente frío
        if row['temp_ac'] >= TEMP_AC_POCO_FRIA:
            señales_calor += 1

        # Para enfriar fuerte en calor moderado,
        # se requieren al menos 2 señales adicionales
        if señales_calor >= 2:
            return 'enfriar_fuerte'
        else:
            return 'mantener'

    # 4. Si hay presencia, pero no hay calor suficiente,
    # se mantiene el funcionamiento normal
    return 'mantener'

df['decision'] = df.apply(decidir, axis=1)
print(df.head(10))
print("\nDistribución:")
print(df['decision'].value_counts())

"""## 2. Modelo Inicial ATMOS v1

Modelo de referencia entrenado con los datos base. Se conserva como antecedente del desarrollo.

"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = df[['presencia', 'temp_ambiente', 'temp_ac', 'delta_t', 'humedad']]
y = df['decision']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

predicciones = modelo.predict(X_test)
precision = accuracy_score(y_test, predicciones)
print(f"Precisión del modelo: {precision * 100:.2f}%")
print("\nDetalle por decisión:")
print(classification_report(y_test, predicciones))

"""### 2.1 Pruebas Manuales Iniciales del Modelo v1

"""

casos = pd.DataFrame([
    [1, 30, 18, 12, 80],   # Hay alguien, mucho calor
    [0, 32, 17, 15, 75],   # Nadie, aunque haga calor
    [1, 24, 22,  2, 65],   # Hay alguien, ambiente agradable
    [1, 28, 20,  8, 70],   # Hay alguien, calor moderado
], columns=['presencia', 'temp_ambiente', 'temp_ac', 'delta_t', 'humedad'])

decisiones = modelo.predict(casos)

for i, decision in enumerate(decisiones):
    print(f"Caso {i+1}: {decision.upper()}")

"""### 2.2 Análisis de Importancia de Variables del Modelo v1

"""

import matplotlib.pyplot as plt

importancias = modelo.feature_importances_
variables = ['presencia', 'temp_ambiente', 'temp_ac', 'delta_t', 'humedad']

plt.figure(figsize=(9, 5))
plt.bar(variables, importancias, color=['#2ecc71', '#e74c3c', '#3498db', '#9b59b6', '#f39c12'])
plt.title('Variables que más influyen en la decisión de ATMOS')
plt.ylabel('Importancia')
plt.xlabel('Variable')
plt.tight_layout()
plt.savefig('importancia_atmos.png')
plt.show()

"""## 3. Generación de Datos Adicionales para Entrenamiento y Robustez

Se agregan datos más variados y una zona frontera balanceada para reforzar casos ambiguos entre `mantener` y `enfriar_fuerte`.

"""

# Datos adicionales más complejos y ambiguos
np.random.seed(99)
n2 = 1000

presencia2 = np.random.randint(0, 2, n2)
temp_ambiente2 = np.random.uniform(20, 38, n2)
temp_ac2 = np.random.uniform(14, 28, n2)
delta_t2 = temp_ambiente2 - temp_ac2
humedad2 = np.random.uniform(40, 95, n2)

df2 = pd.DataFrame({
    'presencia': presencia2,
    'temp_ambiente': temp_ambiente2,
    'temp_ac': temp_ac2,
    'delta_t': delta_t2,
    'humedad': humedad2
})

df2['decision'] = df2.apply(decidir, axis=1)


# ==========================================
# DATOS ADICIONALES DE ZONA FRONTERA BALANCEADA
# ==========================================

np.random.seed(77)
n_frontera = 200

# ------------------------------
# Casos frontera que deberían enfriar fuerte
# ------------------------------

n_fuerte = n_frontera // 2

presencia_f1 = np.ones(n_fuerte, dtype=int)
temp_ambiente_f1 = np.random.uniform(28.5, 30.0, n_fuerte)
temp_ac_f1 = np.random.uniform(22.0, 23.5, n_fuerte)
humedad_f1 = np.random.uniform(70, 85, n_fuerte)
delta_t_f1 = temp_ambiente_f1 - temp_ac_f1

df_frontera_fuerte = pd.DataFrame({
    'presencia': presencia_f1,
    'temp_ambiente': temp_ambiente_f1,
    'temp_ac': temp_ac_f1,
    'delta_t': delta_t_f1,
    'humedad': humedad_f1
})

df_frontera_fuerte['decision'] = df_frontera_fuerte.apply(decidir, axis=1)


# ------------------------------
# Casos frontera que deberían mantenerse
# ------------------------------

n_mantener = n_frontera // 2

presencia_f2 = np.ones(n_mantener, dtype=int)
temp_ambiente_f2 = np.random.uniform(28.0, 29.8, n_mantener)
temp_ac_f2 = np.random.uniform(18.0, 21.5, n_mantener)
humedad_f2 = np.random.uniform(55, 68, n_mantener)
delta_t_f2 = temp_ambiente_f2 - temp_ac_f2

df_frontera_mantener = pd.DataFrame({
    'presencia': presencia_f2,
    'temp_ambiente': temp_ambiente_f2,
    'temp_ac': temp_ac_f2,
    'delta_t': delta_t_f2,
    'humedad': humedad_f2
})

df_frontera_mantener['decision'] = df_frontera_mantener.apply(decidir, axis=1)


# ------------------------------
# Unión de casos frontera
# ------------------------------

df_frontera = pd.concat(
    [df_frontera_fuerte, df_frontera_mantener],
    ignore_index=True
)

print("Distribución de datos frontera balanceada:")
print(df_frontera['decision'].value_counts())


# Combinar datos originales, datos nuevos y datos frontera
df_total = pd.concat([df, df2, df_frontera], ignore_index=True)

print(f"Datos originales: {len(df)}")
print(f"Datos nuevos: {len(df2)}")
print(f"Total combinado: {len(df_total)}")
print("\nDistribución total:")
print(df_total['decision'].value_counts())

"""## 4. Entrenamiento y Evaluación del Modelo Final ATMOS v2

Aquí se entrena el modelo principal `modelo_v2` usando el dataset combinado `df_total`.

"""

X_total = df_total[['presencia', 'temp_ambiente', 'temp_ac', 'delta_t', 'humedad']]
y_total = df_total['decision']

X_train2, X_test2, y_train2, y_test2 = train_test_split(X_total, y_total, test_size=0.2, random_state=42)

modelo_v2 = RandomForestClassifier(n_estimators=100, random_state=42)
modelo_v2.fit(X_train2, y_train2)

predicciones2 = modelo_v2.predict(X_test2)
precision2 = accuracy_score(y_test2, predicciones2)
print(f"Precisión modelo v2 ({len(df_total)} datos): {precision2 * 100:.2f}%")
print("\nDetalle por decisión:")
print(classification_report(y_test2, predicciones2))

import joblib

# Guardar el modelo entrenado en un archivo
joblib.dump(modelo_v2, "modelo_atmos.pkl")

print("Modelo ATMOS exportado correctamente como modelo_atmos.pkl")

#from google.colab import files

#files.download("modelo_atmos.pkl")

"""## 5. Pruebas de Robustez del Modelo

Estas pruebas evalúan cómo responde el modelo ante datos ruidosos y escenarios extremos.

### 5.1 Prueba con Datos Ruidosos
"""

# Casos ambiguos y ruidosos que confunden al modelo
np.random.seed(55)
n3 = 500

# Temperaturas justo en el límite (alrededor de 27°C)
temp_ambiente3 = np.random.uniform(25, 29, n3)
temp_ac3 = np.random.uniform(20, 27, n3)

humedad3 = np.random.uniform(40, 95, n3)
presencia3 = np.random.randint(0, 2, n3)

ruido = np.random.normal(0, 1.5, n3)
temp_ambiente3 = temp_ambiente3 + ruido

delta_t3 = temp_ambiente3 - temp_ac3

df3 = pd.DataFrame({
    'presencia': presencia3,
    'temp_ambiente': temp_ambiente3,
    'temp_ac': temp_ac3,
    'delta_t': delta_t3,
    'humedad': humedad3
})

df3['decision'] = df3.apply(decidir, axis=1)

# Entrenar con datos limpios, probar con datos ruidosos
X_ruidoso = df3[['presencia', 'temp_ambiente', 'temp_ac', 'delta_t', 'humedad']]
y_ruidoso = df3['decision']

predicciones_ruido = modelo_v2.predict(X_ruidoso)
precision_ruido = accuracy_score(y_ruidoso, predicciones_ruido)
print(f"Precisión con datos ruidosos: {precision_ruido * 100:.2f}%")
print("\nDetalle:")
print(classification_report(y_ruidoso, predicciones_ruido))

# ==============================
# MATRIZ DE CONFUSIÓN - DATOS RUIDOSOS
# ==============================

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pandas as pd

labels = ['apagar', 'enfriar_fuerte', 'mantener']

cm = confusion_matrix(y_ruidoso, predicciones_ruido, labels=labels)

cm_df = pd.DataFrame(
    cm,
    index=['Real apagar', 'Real enfriar_fuerte', 'Real mantener'],
    columns=['Pred apagar', 'Pred enfriar_fuerte', 'Pred mantener']
)

print("\nMatriz de confusión - Datos ruidosos:")
print(cm_df)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot()
plt.title("Matriz de confusión - Datos ruidosos")
plt.show()

"""### 5.2 Prueba de Estrés con Datos Extremos

"""

np.random.seed(777)
n4 = 2000

# Temperaturas extremas y muy variadas
temp_ambiente4 = np.random.uniform(18, 40, n4)
temp_ac4 = np.random.uniform(12, 30, n4)
humedad4 = np.random.uniform(30, 98, n4)
presencia4 = np.random.randint(0, 2, n4)

# Ruido más agresivo que antes (±2.5°C)
ruido4 = np.random.normal(0, 2.5, n4)
temp_ambiente4 = temp_ambiente4 + ruido4

# Casos trampa: presencia=1 pero temperatura bajísima
# y presencia=0 pero temperatura altísima
for i in range(100):
    idx = np.random.randint(0, n4)
    temp_ambiente4[idx] = np.random.uniform(18, 22)
    presencia4[idx] = 1

for i in range(100):
    idx = np.random.randint(0, n4)
    temp_ambiente4[idx] = np.random.uniform(35, 40)
    presencia4[idx] = 0

delta_t4 = temp_ambiente4 - temp_ac4

df4 = pd.DataFrame({
    'presencia': presencia4,
    'temp_ambiente': temp_ambiente4,
    'temp_ac': temp_ac4,
    'delta_t': delta_t4,
    'humedad': humedad4
})

df4['decision'] = df4.apply(decidir, axis=1)

X_estres = df4[['presencia', 'temp_ambiente', 'temp_ac', 'delta_t', 'humedad']]
y_estres = df4['decision']

predicciones_estres = modelo_v2.predict(X_estres)
precision_estres = accuracy_score(y_estres, predicciones_estres)
print(f"Precisión bajo prueba de estrés: {precision_estres * 100:.2f}%")
print("\nDetalle:")
print(classification_report(y_estres, predicciones_estres))

"""## 6. Funciones de Operación del Sistema ATMOS

Funciones que permiten usar el modelo con lecturas individuales, aplicar el temporizador externo y traducir la decisión a una acción simulada del aire acondicionado.

"""

# ==========================================
# CONFIGURACIÓN DE ACCIONES DEL AIRE ATMOS
# ==========================================

TEMP_MANTENER = 24
TEMP_ENFRIAR_MODERADO = 23
TEMP_ENFRIAR_FUERTE = 22

TIEMPO_ESPERA_APAGADO = 10  # minutos sin presencia antes de apagar


# ==========================================
# 1. FUNCIÓN PARA PREDECIR UNA SOLA LECTURA
# ==========================================

def predecir_lectura(modelo, presencia, temp_ambiente, temp_ac, humedad):
    """
    Recibe una lectura individual de sensores y devuelve la decisión del modelo ML.
    """

    delta_t = temp_ambiente - temp_ac

    lectura = pd.DataFrame([{
        'presencia': presencia,
        'temp_ambiente': temp_ambiente,
        'temp_ac': temp_ac,
        'delta_t': delta_t,
        'humedad': humedad
    }])

    decision_ml = modelo.predict(lectura)[0]

    return decision_ml, delta_t


# ==================================================
# 2. FUNCIÓN DE TEMPORIZADOR FUERA DEL MODELO ML
# ==================================================

def aplicar_temporizador(decision_ml, presencia, minutos_sin_presencia):
    """
    Aplica la lógica de espera antes de apagar el aire.
    Esta función NO pertenece al modelo ML.
    Es una capa de control del sistema.
    """

    if presencia == 0 and decision_ml == 'apagar':

        if minutos_sin_presencia >= TIEMPO_ESPERA_APAGADO:
            return 'apagar'

        else:
            return 'esperar_apagado'

    return decision_ml


# ==================================================
# 3. FUNCIÓN PARA TRADUCIR DECISIÓN A ACCIÓN DEL AC
# ==================================================

def traducir_decision_ac(decision_final, temp_ambiente):
    """
    Traduce la decisión final del sistema en una acción entendible para el AC.
    Por ahora es una simulación, no envía señal IR real.
    """

    if decision_final == 'apagar':
        return {
            'estado_ac': 'apagado',
            'temperatura_objetivo': None,
            'modo': 'off',
            'ventilacion': 'apagada',
            'accion': 'Enviar comando IR para apagar el aire acondicionado'
        }

    elif decision_final == 'esperar_apagado':
        return {
            'estado_ac': 'encendido',
            'temperatura_objetivo': 'sin cambio',
            'modo': 'sin cambio',
            'ventilacion': 'sin cambio',
            'accion': 'No enviar nuevo comando. Esperar hasta cumplir los 10 minutos sin presencia'
        }

    elif decision_final == 'mantener':
        return {
            'estado_ac': 'encendido',
            'temperatura_objetivo': TEMP_MANTENER,
            'modo': 'cool',
            'ventilacion': 'automatica',
            'accion': f'Mantener el aire acondicionado en {TEMP_MANTENER}°C'
        }

    elif decision_final == 'enfriar_fuerte':

        if temp_ambiente >= 30:
            temperatura = TEMP_ENFRIAR_FUERTE
            ventilacion = 'alta'
        else:
            temperatura = TEMP_ENFRIAR_MODERADO
            ventilacion = 'media'

        return {
            'estado_ac': 'encendido',
            'temperatura_objetivo': temperatura,
            'modo': 'cool',
            'ventilacion': ventilacion,
            'accion': f'Configurar el aire a {temperatura}°C con ventilación {ventilacion}'
        }

"""## 7. Módulo de Detección de Fallas del AC

Regla lógica independiente del modelo ML para identificar posible bajo rendimiento del aire acondicionado.

"""

# ==========================================
# MÓDULO DE DETECCIÓN DE FALLAS DEL AC
# ==========================================

TIEMPO_MINIMO_FALLA = 30          # minutos en enfriar_fuerte antes de evaluar falla
DESCENSO_MINIMO_ESPERADO = 3      # °C que debería bajar el salón
TEMP_AC_ALTA = 23                 # si el aire sale a 23°C o más, puede indicar bajo rendimiento


def detectar_falla_ac(decision_final, minutos_enfriando, temp_inicio, temp_actual, temp_ac_actual):
    """
    Evalúa si el aire acondicionado podría estar fallando.

    Esta lógica se activa solo cuando el sistema lleva cierto tiempo en 'enfriar_fuerte'.
    Si después de 30 minutos la temperatura ambiente no baja al menos 3°C,
    se genera una alerta de posible falla o bajo rendimiento.
    """

    # Si el sistema no está en enfriar_fuerte, no se evalúa falla
    if decision_final != 'enfriar_fuerte':
        return {
            'estado_falla': 'no_aplica',
            'alerta': False,
            'mensaje': 'No se evalúa falla porque el sistema no está en modo enfriar_fuerte.'
        }

    # Si todavía no han pasado 30 minutos, solo se sigue monitoreando
    if minutos_enfriando < TIEMPO_MINIMO_FALLA:
        return {
            'estado_falla': 'monitoreando',
            'alerta': False,
            'mensaje': f'El sistema lleva {minutos_enfriando} minutos enfriando. Aún no se evalúa falla.'
        }

    # Calcular cuánto bajó la temperatura ambiente
    descenso_temp = temp_inicio - temp_actual

    # Caso de posible falla
    if descenso_temp < DESCENSO_MINIMO_ESPERADO:
        if temp_ac_actual >= TEMP_AC_ALTA:
            mensaje = (
                f'Posible falla del AC: después de {minutos_enfriando} minutos en enfriar_fuerte, '
                f'la temperatura solo bajó {descenso_temp:.1f}°C y el aire del AC sale a {temp_ac_actual}°C.'
            )
        else:
            mensaje = (
                f'Posible bajo rendimiento: después de {minutos_enfriando} minutos en enfriar_fuerte, '
                f'la temperatura solo bajó {descenso_temp:.1f}°C.'
            )

        return {
            'estado_falla': 'posible_falla',
            'alerta': True,
            'descenso_temperatura': round(descenso_temp, 2),
            'mensaje': mensaje
        }

    # Caso normal: sí bajó lo suficiente
    return {
        'estado_falla': 'funcionamiento_normal',
        'alerta': False,
        'descenso_temperatura': round(descenso_temp, 2),
        'mensaje': f'El AC funciona correctamente. La temperatura bajó {descenso_temp:.1f}°C.'
    }

"""### 7.1 Prueba del Módulo: Posible Falla

"""

# ==========================================
# PRUEBA DEL MÓDULO DE DETECCIÓN DE FALLAS
# ==========================================

# Simulación:
# El sistema lleva 30 minutos en enfriar_fuerte.
# El salón empezó en 30°C y solo bajó a 28.5°C.
# Eso significa que bajó 1.5°C, menos de los 3°C esperados.

decision_final = 'enfriar_fuerte'
minutos_enfriando = 30
temp_inicio = 30.0
temp_actual = 28.5
temp_ac_actual = 24.0

resultado_falla = detectar_falla_ac(
    decision_final,
    minutos_enfriando,
    temp_inicio,
    temp_actual,
    temp_ac_actual
)

print("=== DETECCIÓN DE FALLAS ATMOS ===")
print("Decisión final:", decision_final)
print("Minutos enfriando:", minutos_enfriando)
print("Temperatura inicial:", temp_inicio)
print("Temperatura actual:", temp_actual)
print("Temperatura del AC:", temp_ac_actual)
print("--------------------------------")
print("Estado:", resultado_falla['estado_falla'])
print("Alerta:", resultado_falla['alerta'])
print("Mensaje:", resultado_falla['mensaje'])

"""### 7.2 Prueba del Módulo: Funcionamiento Normal

"""

# ==========================================
# PRUEBA DE FUNCIONAMIENTO NORMAL DEL AC
# ==========================================

decision_final = 'enfriar_fuerte'
minutos_enfriando = 30
temp_inicio = 30.0
temp_actual = 26.5
temp_ac_actual = 18.0

resultado_falla = detectar_falla_ac(
    decision_final,
    minutos_enfriando,
    temp_inicio,
    temp_actual,
    temp_ac_actual
)

print("=== PRUEBA DE FUNCIONAMIENTO NORMAL ===")
print("Decisión final:", decision_final)
print("Minutos enfriando:", minutos_enfriando)
print("Temperatura inicial:", temp_inicio)
print("Temperatura actual:", temp_actual)
print("Temperatura del AC:", temp_ac_actual)
print("--------------------------------")
print("Estado:", resultado_falla['estado_falla'])
print("Alerta:", resultado_falla['alerta'])
print("Mensaje:", resultado_falla['mensaje'])

"""## 7.5 Función Principal del Sistema ATMOS"""

# ==========================================
# VALIDACIÓN DE ENTRADAS DEL SISTEMA ATMOS
# ==========================================

def validar_lectura(presencia, temp_ambiente, temp_ac, humedad, minutos_sin_presencia=0):
    """
    Valida que los datos recibidos por el sistema sean coherentes antes de pasarlos al modelo.
    """

    errores = []

    if presencia not in [0, 1]:
        errores.append("La variable 'presencia' debe ser 0 o 1.")

    if temp_ambiente < 10 or temp_ambiente > 45:
        errores.append("La temperatura ambiente está fuera de un rango lógico (10°C a 45°C).")

    if temp_ac < 5 or temp_ac > 35:
        errores.append("La temperatura del AC está fuera de un rango lógico (5°C a 35°C).")

    if humedad < 0 or humedad > 100:
        errores.append("La humedad debe estar entre 0% y 100%.")

    if minutos_sin_presencia < 0:
        errores.append("Los minutos sin presencia no pueden ser negativos.")

    return {
        "valido": len(errores) == 0,
        "errores": errores
    }


# ==========================================
# CAPA DE SEGURIDAD PARA CASOS FRONTERA
# ==========================================

def aplicar_capa_seguridad(decision_ml, presencia, temp_ambiente, temp_ac, delta_t, humedad):
    """
    Evita que el modelo mande a enfriar fuerte en casos frontera donde las condiciones
    no son suficientemente claras.

    Esta capa no reemplaza al modelo, solo actúa como protección para evitar
    enfriamientos innecesarios.
    """

    caso = pd.Series({
        "presencia": presencia,
        "temp_ambiente": temp_ambiente,
        "temp_ac": temp_ac,
        "delta_t": delta_t,
        "humedad": humedad
    })

    decision_regla = decidir(caso)

    # Protección: si no hay presencia, se mantiene la recomendación de apagar.
    if presencia == 0:
        return decision_ml, "Sin presencia detectada. Se mantiene la decisión del modelo."

    # Protección: si el modelo manda apagar con presencia, se evita apagar.
    if presencia == 1 and decision_ml == "apagar":
        return "mantener", "Capa de seguridad: había presencia, se evita apagar el AC."

    # Protección principal: evitar enfriar fuerte si la regla base dice mantener.
    if decision_ml == "enfriar_fuerte" and decision_regla == "mantener":
        return "mantener", "Capa de seguridad: caso frontera. Se evita enfriar fuerte innecesariamente."

    return decision_ml, "La decisión del modelo fue aceptada por la capa de seguridad."


# ==========================================
# FUNCIÓN PRINCIPAL DEL SISTEMA ATMOS
# ==========================================

def ejecutar_atmos(
    modelo,
    presencia,
    temp_ambiente,
    temp_ac,
    humedad,
    minutos_sin_presencia=0,
    minutos_enfriando=0,
    temp_inicio=None,
    temp_actual=None,
    temp_ac_actual=None,
    usar_capa_seguridad=True
):
    """
    Ejecuta el flujo completo de ATMOS:

    1. Valida datos de entrada.
    2. Predice la decisión con el modelo ML.
    3. Aplica capa de seguridad.
    4. Aplica temporizador de ausencia.
    5. Traduce la decisión a una acción para el AC.
    6. Evalúa posible falla del aire acondicionado.
    """

    validacion = validar_lectura(
        presencia,
        temp_ambiente,
        temp_ac,
        humedad,
        minutos_sin_presencia
    )

    if not validacion["valido"]:
        return {
            "valido": False,
            "errores": validacion["errores"],
            "mensaje": "La lectura no pudo procesarse porque contiene datos inválidos."
        }

    # Predicción del modelo
    decision_ml, delta_t = predecir_lectura(
        modelo,
        presencia,
        temp_ambiente,
        temp_ac,
        humedad
    )

    # Probabilidades del modelo
    lectura_prob = pd.DataFrame([{
        "presencia": presencia,
        "temp_ambiente": temp_ambiente,
        "temp_ac": temp_ac,
        "delta_t": delta_t,
        "humedad": humedad
    }])

    probabilidades_array = modelo.predict_proba(lectura_prob)[0]

    probabilidades = {
        clase: float(round(prob * 100, 2))
        for clase, prob in zip(modelo.classes_, probabilidades_array)
    }

    # Capa de seguridad
    if usar_capa_seguridad:
        decision_segura, mensaje_seguridad = aplicar_capa_seguridad(
            decision_ml,
            presencia,
            temp_ambiente,
            temp_ac,
            delta_t,
            humedad
        )
    else:
        decision_segura = decision_ml
        mensaje_seguridad = "Capa de seguridad desactivada."

    # Temporizador
    decision_final = aplicar_temporizador(
        decision_segura,
        presencia,
        minutos_sin_presencia
    )

    # Traducción a acción del AC
    accion_ac = traducir_decision_ac(
        decision_final,
        temp_ambiente
    )

    # Detección de fallas
    if temp_inicio is not None and temp_actual is not None and temp_ac_actual is not None:
        falla_ac = detectar_falla_ac(
            decision_final,
            minutos_enfriando,
            temp_inicio,
            temp_actual,
            temp_ac_actual
        )
    else:
        falla_ac = {
            "estado_falla": "no_evaluada",
            "alerta": False,
            "mensaje": "No se evaluó falla porque no se proporcionaron datos históricos de enfriamiento."
        }

    return {
        "valido": True,
        "lectura": {
            "presencia": presencia,
            "temp_ambiente": temp_ambiente,
            "temp_ac": temp_ac,
            "delta_t": round(delta_t, 2),
            "humedad": humedad,
            "minutos_sin_presencia": minutos_sin_presencia
        },
        "modelo": {
            "decision_ml": decision_ml,
            "probabilidades": probabilidades
        },
        "seguridad": {
            "decision_segura": decision_segura,
            "mensaje": mensaje_seguridad
        },
        "control": {
            "decision_final": decision_final,
            "accion_ac": accion_ac
        },
        "deteccion_fallas": falla_ac
    }

# ==========================================
# PRUEBA DE LA FUNCIÓN PRINCIPAL ATMOS
# ==========================================

resultado_atmos = ejecutar_atmos(
    modelo=modelo_v2,
    presencia=1,
    temp_ambiente=29.5,
    temp_ac=22.5,
    humedad=75,
    minutos_sin_presencia=0,
    minutos_enfriando=0
)

resultado_atmos

import json

print(json.dumps(resultado_atmos, indent=4, ensure_ascii=False))

# ==========================================
# PRUEBA FINAL DE INTEGRACIÓN ATMOS
# ==========================================
# Esta prueba usa únicamente la función principal ejecutar_atmos()
# para validar el flujo completo del sistema.

casos_integracion = [
    {
        "caso": "Salón ocupado con temperatura cómoda",
        "presencia": 1,
        "temp_ambiente": 24.5,
        "temp_ac": 18.5,
        "humedad": 60,
        "minutos_sin_presencia": 0
    },
    {
        "caso": "Salón ocupado con calor moderado",
        "presencia": 1,
        "temp_ambiente": 29.5,
        "temp_ac": 22.5,
        "humedad": 75,
        "minutos_sin_presencia": 0
    },
    {
        "caso": "Salón ocupado con calor fuerte",
        "presencia": 1,
        "temp_ambiente": 31.0,
        "temp_ac": 23.0,
        "humedad": 75,
        "minutos_sin_presencia": 0
    },
    {
        "caso": "Salón vacío por 5 minutos",
        "presencia": 0,
        "temp_ambiente": 27.0,
        "temp_ac": 20.0,
        "humedad": 65,
        "minutos_sin_presencia": 5
    },
    {
        "caso": "Salón vacío por 10 minutos",
        "presencia": 0,
        "temp_ambiente": 27.0,
        "temp_ac": 20.0,
        "humedad": 65,
        "minutos_sin_presencia": 10
    },
    {
        "caso": "Posible falla del AC",
        "presencia": 1,
        "temp_ambiente": 30.0,
        "temp_ac": 24.0,
        "humedad": 80,
        "minutos_sin_presencia": 0,
        "minutos_enfriando": 30,
        "temp_inicio": 30.0,
        "temp_actual": 28.5,
        "temp_ac_actual": 24.0
    }
]

resultados_integracion = []

for caso in casos_integracion:

    resultado = ejecutar_atmos(
        modelo=modelo_v2,
        presencia=caso["presencia"],
        temp_ambiente=caso["temp_ambiente"],
        temp_ac=caso["temp_ac"],
        humedad=caso["humedad"],
        minutos_sin_presencia=caso["minutos_sin_presencia"],
        minutos_enfriando=caso.get("minutos_enfriando", 0),
        temp_inicio=caso.get("temp_inicio", None),
        temp_actual=caso.get("temp_actual", None),
        temp_ac_actual=caso.get("temp_ac_actual", None)
    )

    fila = {
        "caso": caso["caso"],
        "valido": resultado["valido"],
        "decision_ml": resultado["modelo"]["decision_ml"],
        "decision_segura": resultado["seguridad"]["decision_segura"],
        "decision_final": resultado["control"]["decision_final"],
        "estado_ac": resultado["control"]["accion_ac"]["estado_ac"],
        "temperatura_objetivo": resultado["control"]["accion_ac"]["temperatura_objetivo"],
        "accion": resultado["control"]["accion_ac"]["accion"],
        "alerta_falla": resultado["deteccion_fallas"]["alerta"],
        "estado_falla": resultado["deteccion_fallas"]["estado_falla"]
    }

    resultados_integracion.append(fila)


df_integracion = pd.DataFrame(resultados_integracion)

print("=== PRUEBA FINAL DE INTEGRACIÓN ATMOS ===")
display(df_integracion)

"""## 8. Flujo Completo del Sistema ATMOS y Validación Individual

### 8.1 Prueba Básica del Flujo Completo
"""

# ==========================================
# PRUEBA DE FLUJO COMPLETO ATMOS
# ==========================================

presencia = 1
temp_ambiente = 29.5
temp_ac = 22.5
humedad = 75
minutos_sin_presencia = 0

decision_ml, delta_t = predecir_lectura(
    modelo_v2,
    presencia,
    temp_ambiente,
    temp_ac,
    humedad
)

decision_final = aplicar_temporizador(
    decision_ml,
    presencia,
    minutos_sin_presencia
)

accion_ac = traducir_decision_ac(
    decision_final,
    temp_ambiente
)

print("=== FLUJO ATMOS ===")
print("Presencia:", presencia)
print("Temperatura ambiente:", temp_ambiente)
print("Temperatura AC:", temp_ac)
print("Delta T:", round(delta_t, 2))
print("Humedad:", humedad)
print("Decisión del modelo ML:", decision_ml)
print("Decisión final del sistema:", decision_final)
print("Acción para el AC:")
print(accion_ac)

presencia = 0
temp_ambiente = 27
temp_ac = 20
humedad = 65
minutos_sin_presencia = 5

decision_ml, delta_t = predecir_lectura(
    modelo_v2,
    presencia,
    temp_ambiente,
    temp_ac,
    humedad
)

decision_final = aplicar_temporizador(
    decision_ml,
    presencia,
    minutos_sin_presencia
)

accion_ac = traducir_decision_ac(
    decision_final,
    temp_ambiente
)

print("=== PRUEBA SIN PRESENCIA ===")
print("Minutos sin presencia:", minutos_sin_presencia)
print("Decisión del modelo ML:", decision_ml)
print("Decisión final del sistema:", decision_final)
print("Acción para el AC:")
print(accion_ac)

"""### 8.2 Validación Individual: Regla vs Modelo

"""

#Validacion individual: Regla vs Modelo
# ==========================================
# VALIDACIÓN INDIVIDUAL: REGLA VS MODELO
# ==========================================

# Cambia estos valores para probar diferentes casos
presencia = 1
temp_ambiente = 28.7
temp_ac = 21.8
humedad = 69
minutos_sin_presencia = 0

# El delta_t siempre se calcula a partir de las temperaturas
delta_t = temp_ambiente - temp_ac

# Decisión según el modelo ML
decision_ml, delta_t = predecir_lectura(
    modelo_v2,
    presencia,
    temp_ambiente,
    temp_ac,
    humedad
)

# ==========================================
# PROBABILIDADES DEL MODELO
# ==========================================

lectura_prob = pd.DataFrame([{
    'presencia': presencia,
    'temp_ambiente': temp_ambiente,
    'temp_ac': temp_ac,
    'delta_t': delta_t,
    'humedad': humedad
}])

probabilidades = modelo_v2.predict_proba(lectura_prob)[0]

print("\nProbabilidades del modelo:")
for clase, prob in zip(modelo_v2.classes_, probabilidades):
    print(f"{clase}: {prob * 100:.2f}%")

# Decisión según la regla original decidir()
caso_prueba = pd.Series({
    'presencia': presencia,
    'temp_ambiente': temp_ambiente,
    'temp_ac': temp_ac,
    'delta_t': delta_t,
    'humedad': humedad
})

decision_regla = decidir(caso_prueba)

# Aplicar temporizador
decision_final = aplicar_temporizador(
    decision_ml,
    presencia,
    minutos_sin_presencia
)

# Traducir a acción del AC
accion_ac = traducir_decision_ac(
    decision_final,
    temp_ambiente
)

print("=== VALIDACIÓN INDIVIDUAL ATMOS ===")
print("Presencia:", presencia)
print("Temperatura ambiente:", temp_ambiente)
print("Temperatura AC:", temp_ac)
print("Delta T:", round(delta_t, 2))
print("Humedad:", humedad)
print("Minutos sin presencia:", minutos_sin_presencia)
print("-----------------------------------")
print("Decisión según la regla decidir():", decision_regla)
print("Decisión según el modelo ML:", decision_ml)
print("Decisión final del sistema:", decision_final)
print("Acción para el AC:")
print(accion_ac)

"""## 9. Simulación de Casos de Demostración

Casos simulados para mostrar el comportamiento del sistema en escenarios representativos.

"""

# ==========================================
# CASOS REALES SIMULADOS DE DEMOSTRACIÓN ATMOS
# ==========================================

casos_demo = [
    {
        "nombre": "Caso 1 - Salón ocupado y temperatura cómoda",
        "presencia": 1,
        "temp_ambiente": 24.5,
        "temp_ac": 18.5,
        "humedad": 60,
        "minutos_sin_presencia": 0
    },
    {
        "nombre": "Caso 2 - Salón ocupado con calor moderado",
        "presencia": 1,
        "temp_ambiente": 29.5,
        "temp_ac": 22.5,
        "humedad": 75,
        "minutos_sin_presencia": 0
    },
    {
        "nombre": "Caso 3 - Salón ocupado con calor fuerte",
        "presencia": 1,
        "temp_ambiente": 31.0,
        "temp_ac": 23.0,
        "humedad": 75,
        "minutos_sin_presencia": 0
    },
    {
        "nombre": "Caso 4 - Salón vacío por 5 minutos",
        "presencia": 0,
        "temp_ambiente": 27.0,
        "temp_ac": 20.0,
        "humedad": 65,
        "minutos_sin_presencia": 5
    },
    {
        "nombre": "Caso 5 - Salón vacío por 10 minutos",
        "presencia": 0,
        "temp_ambiente": 27.0,
        "temp_ac": 20.0,
        "humedad": 65,
        "minutos_sin_presencia": 10
    },
    {
        "nombre": "Caso 6 - Posible bajo rendimiento del AC",
        "presencia": 1,
        "temp_ambiente": 30.0,
        "temp_ac": 24.0,
        "humedad": 80,
        "minutos_sin_presencia": 0
    }
]


for caso in casos_demo:
    presencia = caso["presencia"]
    temp_ambiente = caso["temp_ambiente"]
    temp_ac = caso["temp_ac"]
    humedad = caso["humedad"]
    minutos_sin_presencia = caso["minutos_sin_presencia"]

    decision_ml, delta_t = predecir_lectura(
        modelo_v2,
        presencia,
        temp_ambiente,
        temp_ac,
        humedad
    )

    decision_final = aplicar_temporizador(
        decision_ml,
        presencia,
        minutos_sin_presencia
    )

    accion_ac = traducir_decision_ac(
        decision_final,
        temp_ambiente
    )

    lectura_prob = pd.DataFrame([{
        'presencia': presencia,
        'temp_ambiente': temp_ambiente,
        'temp_ac': temp_ac,
        'delta_t': delta_t,
        'humedad': humedad
    }])

    probabilidades = modelo_v2.predict_proba(lectura_prob)[0]

    print("==========================================")
    print(caso["nombre"])
    print("==========================================")
    print("Presencia:", presencia)
    print("Temperatura ambiente:", temp_ambiente)
    print("Temperatura AC:", temp_ac)
    print("Delta T:", round(delta_t, 2))
    print("Humedad:", humedad)
    print("Minutos sin presencia:", minutos_sin_presencia)
    print("------------------------------------------")
    print("Probabilidades del modelo:")
    for clase, prob in zip(modelo_v2.classes_, probabilidades):
        print(f"{clase}: {prob * 100:.2f}%")
    print("------------------------------------------")
    print("Decisión del modelo ML:", decision_ml)
    print("Decisión final del sistema:", decision_final)
    print("Acción para el AC:")
    print(accion_ac)
    print("\n")

"""## 10. Simulación del temporizador de ausencia

Demo con temporizador corto en segundos para representar el comportamiento del sistema ante presencia y ausencia.

"""

# ==========================================
# 10. SIMULACIÓN DEL TEMPORIZADOR DE AUSENCIA ATMOS
# ==========================================
# Esta simulación muestra cómo ATMOS responde cuando una persona entra,
# sale momentáneamente y luego se cumple el tiempo de espera para apagar.
#
# Nota:
# En esta demo se usan 10 segundos para no esperar 10 minutos en Colab.
# En producción, el tiempo real sería 10 minutos.

import time
from datetime import datetime

# Estado simulado del sistema
estado_tiempo_real = {
    "ultima_presencia": None,
    "ultimo_resultado": None
}

TIEMPO_GRACIA_DEMO_SEGUNDOS = 10  # demo rápida
TIEMPO_REAL_PRODUCCION_MINUTOS = 10  # valor real esperado del sistema


def procesar_lectura_tiempo_real(presencia, temp_ambiente, temp_ac, humedad):
    """
    Simula el procesamiento de una lectura en tiempo real usando la función principal ejecutar_atmos().
    """

    ahora = datetime.now()

    # Caso 1: hay presencia
    if presencia == 1:
        estado_tiempo_real["ultima_presencia"] = ahora

        resultado = ejecutar_atmos(
            modelo=modelo_v2,
            presencia=presencia,
            temp_ambiente=temp_ambiente,
            temp_ac=temp_ac,
            humedad=humedad,
            minutos_sin_presencia=0
        )

        estado_tiempo_real["ultimo_resultado"] = resultado
        return resultado

    # Caso 2: no hay presencia y nunca se registró presencia antes
    if estado_tiempo_real["ultima_presencia"] is None:
        resultado = ejecutar_atmos(
            modelo=modelo_v2,
            presencia=0,
            temp_ambiente=temp_ambiente,
            temp_ac=temp_ac,
            humedad=humedad,
            minutos_sin_presencia=TIEMPO_REAL_PRODUCCION_MINUTOS
        )

        estado_tiempo_real["ultimo_resultado"] = resultado
        return resultado

    # Caso 3: no hay presencia, pero se calcula cuánto tiempo ha pasado
    segundos_sin_presencia = (ahora - estado_tiempo_real["ultima_presencia"]).seconds

    if segundos_sin_presencia < TIEMPO_GRACIA_DEMO_SEGUNDOS:
        segundos_restantes = TIEMPO_GRACIA_DEMO_SEGUNDOS - segundos_sin_presencia

        print(
            f"  ⏳ Sin presencia hace {segundos_sin_presencia}s, "
            f"esperando {segundos_restantes}s más antes de apagar..."
        )

        # En demo: todavía no se cumple el tiempo.
        # Para ejecutar_atmos(), esto representa que aún no pasaron los 10 minutos reales.
        minutos_sin_presencia = 0

    else:
        # En demo: ya se cumplió el tiempo.
        # Para ejecutar_atmos(), esto representa que ya pasaron los 10 minutos reales.
        minutos_sin_presencia = TIEMPO_REAL_PRODUCCION_MINUTOS

    resultado = ejecutar_atmos(
        modelo=modelo_v2,
        presencia=0,
        temp_ambiente=temp_ambiente,
        temp_ac=temp_ac,
        humedad=humedad,
        minutos_sin_presencia=minutos_sin_presencia
    )

    estado_tiempo_real["ultimo_resultado"] = resultado
    return resultado


def mostrar_resultado_tiempo_real(resultado):
    """
    Imprime de forma clara el resultado de ATMOS en la simulación.
    """

    print("   Decisión ML:", resultado["modelo"]["decision_ml"])
    print("   Decisión segura:", resultado["seguridad"]["decision_segura"])
    print("   Decisión final:", resultado["control"]["decision_final"])
    print("   Estado del AC:", resultado["control"]["accion_ac"]["estado_ac"])
    print("   Temperatura objetivo:", resultado["control"]["accion_ac"]["temperatura_objetivo"])
    print("   Acción:", resultado["control"]["accion_ac"]["accion"])


# ==========================================
# SIMULACIÓN
# ==========================================

print("=== SIMULACIÓN DEL TEMPORIZADOR DE AUSENCIA ATMOS ===\n")

print("1. Llega alguien al salón, hace 30°C")
resultado = procesar_lectura_tiempo_real(
    presencia=1,
    temp_ambiente=30,
    temp_ac=18,
    humedad=75
)
mostrar_resultado_tiempo_real(resultado)
print()

time.sleep(3)

print("2. La persona sale: 3 segundos sin presencia")
resultado = procesar_lectura_tiempo_real(
    presencia=0,
    temp_ambiente=30,
    temp_ac=18,
    humedad=75
)
mostrar_resultado_tiempo_real(resultado)
print()

time.sleep(3)

print("3. Siguen pasando 3 segundos más: 6 segundos total sin presencia")
resultado = procesar_lectura_tiempo_real(
    presencia=0,
    temp_ambiente=30,
    temp_ac=18,
    humedad=75
)
mostrar_resultado_tiempo_real(resultado)
print()

print("4. Regresa alguien antes de cumplir el tiempo de apagado")
resultado = procesar_lectura_tiempo_real(
    presencia=1,
    temp_ambiente=30,
    temp_ac=18,
    humedad=75
)
mostrar_resultado_tiempo_real(resultado)
print()

time.sleep(11)

print("5. La persona sale y se cumple el tiempo de espera")
resultado = procesar_lectura_tiempo_real(
    presencia=0,
    temp_ambiente=30,
    temp_ac=18,
    humedad=75
)
mostrar_resultado_tiempo_real(resultado)
print()

"""## 11. Impacto Económico Estimado y Real de ATMOS

### 11.1 Simulación Simple del Impacto Mensual
"""

# ==========================================
# IMPACTO ECONÓMICO ESTIMADO - SALÓN ROBÓTICA
# ==========================================
# Este cálculo estima el ahorro potencial de ATMOS en un solo salón.
# El ahorro depende de los bloques sin clases donde el AC podría quedar encendido.
# Si el AC ya está apagado en esos bloques, no existe ahorro adicional.

# ------------------------------
# Parámetros del horario
# ------------------------------

duracion_bloque_horas = 45 / 60   # cada bloque dura 45 minutos
bloques_totales_semana = 95       # lunes a viernes, sin sábado

# Bloques vacíos totales según el horario descrito
bloques_vacios_totales = {
    "lunes": 5,
    "martes": 4,
    "miercoles": 3,
    "jueves": 6,
    "viernes": 7
}

# Bloques vacíos considerados para ahorro realista/conservador
# Se excluyen bloques donde probablemente el AC ya estaría apagado
# antes de la primera clase o después de la última clase.
bloques_vacios_conservador = {
    "lunes": 5,
    "martes": 4,
    "miercoles": 1,
    "jueves": 6,
    "viernes": 5
}

# Cantidad aproximada de periodos vacíos por semana.
# Cada periodo vacío activa el temporizador de 10 minutos antes de apagar.
periodos_vacios_semana = 7

# ------------------------------
# Parámetros eléctricos
# ------------------------------

consumo_ac_kw = 1.5       # AJUSTAR: potencia aproximada del AC en kW
tarifa_kwh = 0.18         # AJUSTAR: tarifa eléctrica en B/. por kWh
semanas_mes = 4           # mes académico aproximado

# Temporizador de ATMOS
tiempo_espera_apagado_min = 10
tiempo_espera_apagado_horas = tiempo_espera_apagado_min / 60

# ------------------------------
# Cálculos del horario
# ------------------------------

total_bloques_vacios = sum(bloques_vacios_totales.values())
total_bloques_vacios_conservador = sum(bloques_vacios_conservador.values())

horas_totales_semana = bloques_totales_semana * duracion_bloque_horas
horas_vacias_semana = total_bloques_vacios * duracion_bloque_horas
horas_vacias_conservador_semana = total_bloques_vacios_conservador * duracion_bloque_horas

# Descuento por temporizador:
# ATMOS no apaga inmediatamente; espera 10 minutos por cada periodo vacío.
horas_espera_semana = periodos_vacios_semana * tiempo_espera_apagado_horas

horas_ahorro_efectivo_semana = horas_vacias_conservador_semana - horas_espera_semana
horas_ahorro_efectivo_mes = horas_ahorro_efectivo_semana * semanas_mes

# ------------------------------
# Cálculos energéticos y económicos
# ------------------------------

kwh_ahorrados_mes = horas_ahorro_efectivo_mes * consumo_ac_kw
ahorro_mensual = kwh_ahorrados_mes * tarifa_kwh
ahorro_anual = ahorro_mensual * 12

porcentaje_vacio_total = (total_bloques_vacios / bloques_totales_semana) * 100
porcentaje_ahorro_conservador = (horas_ahorro_efectivo_semana / horas_totales_semana) * 100

# ------------------------------
# Resultados
# ------------------------------

print("=== IMPACTO ECONÓMICO ESTIMADO - SALÓN ROBÓTICA ===")
print(f"Bloques totales por semana: {bloques_totales_semana}")
print(f"Horas posibles de operación por semana: {horas_totales_semana:.2f} h")
print()
print(f"Bloques vacíos totales detectados: {total_bloques_vacios}")
print(f"Horas vacías totales por semana: {horas_vacias_semana:.2f} h")
print(f"Porcentaje de bloques vacíos: {porcentaje_vacio_total:.2f}%")
print()
print("Escenario conservador:")
print(f"Bloques vacíos considerados para ahorro: {total_bloques_vacios_conservador}")
print(f"Horas vacías consideradas por semana: {horas_vacias_conservador_semana:.2f} h")
print(f"Horas descontadas por temporizador: {horas_espera_semana:.2f} h/semana")
print(f"Horas efectivas de ahorro por semana: {horas_ahorro_efectivo_semana:.2f} h")
print(f"Horas efectivas de ahorro por mes: {horas_ahorro_efectivo_mes:.2f} h")
print()
print(f"Consumo estimado del AC: {consumo_ac_kw} kW")
print(f"Tarifa eléctrica usada: B/. {tarifa_kwh} por kWh")
print(f"kWh ahorrados al mes: {kwh_ahorrados_mes:.2f} kWh")
print(f"Ahorro mensual estimado: B/. {ahorro_mensual:.2f}")
print(f"Ahorro anual estimado: B/. {ahorro_anual:.2f}")
print()
print(f"Porcentaje efectivo de reducción sobre el horario semanal: {porcentaje_ahorro_conservador:.2f}%")



"""### 11.2 Simulación del Impacto Basado en Decisiones del Modelo

"""

# ==========================================
# 11.2 SIMULACIÓN DEL IMPACTO BASADO EN DECISIONES DEL SISTEMA
# ==========================================
# Esta simulación evalúa cómo se comportaría ATMOS ante lecturas simuladas
# y estima el impacto energético usando la decisión final del sistema.
#
# Importante:
# Este cálculo NO reemplaza el cálculo basado en horario real del salón.
# Es una simulación complementaria basada en decisiones generadas por ATMOS.

np.random.seed(42)

n_sim = 100  # cantidad de lecturas simuladas

# ------------------------------
# Parámetros económicos
# ------------------------------
# Si estas variables ya existen por la sección 11.1, se usan.
# Si no existen, se asignan valores por defecto.

try:
    consumo_ac_kw
except NameError:
    consumo_ac_kw = 1.5

try:
    tarifa_kwh
except NameError:
    tarifa_kwh = 0.18

try:
    horas_totales_semana
except NameError:
    horas_totales_semana = 71.25  # Robótica: 95 bloques x 0.75 h

try:
    semanas_mes
except NameError:
    semanas_mes = 4

cantidad_aires = 1  # cambiar a 2 si el salón tiene dos aires acondicionados

horas_operacion_mes = horas_totales_semana * semanas_mes

# ------------------------------
# Simulación de lecturas
# ------------------------------

registro = []

for i in range(n_sim):
    presencia = np.random.randint(0, 2)
    temp_ambiente = np.random.uniform(22, 35)
    temp_ac = np.random.uniform(16, 26)
    humedad = np.random.uniform(50, 90)

    # Si no hay presencia, simulamos cuántos minutos lleva vacío
    if presencia == 0:
        minutos_sin_presencia = np.random.randint(0, 16)
    else:
        minutos_sin_presencia = 0

    resultado = ejecutar_atmos(
        modelo=modelo_v2,
        presencia=presencia,
        temp_ambiente=temp_ambiente,
        temp_ac=temp_ac,
        humedad=humedad,
        minutos_sin_presencia=minutos_sin_presencia
    )

    accion_ac = resultado["control"]["accion_ac"]

    registro.append({
        "lectura": i + 1,
        "presencia": presencia,
        "temp_ambiente": round(temp_ambiente, 1),
        "temp_ac": round(temp_ac, 1),
        "humedad": round(humedad, 1),
        "minutos_sin_presencia": minutos_sin_presencia,
        "decision_ml": resultado["modelo"]["decision_ml"],
        "decision_segura": resultado["seguridad"]["decision_segura"],
        "decision_final": resultado["control"]["decision_final"],
        "estado_ac": accion_ac["estado_ac"],
        "temperatura_objetivo": accion_ac["temperatura_objetivo"],
        "accion": accion_ac["accion"]
    })

df_registro = pd.DataFrame(registro)

print("=== REGISTRO DE DECISIONES DEL SISTEMA ATMOS ===")
print(df_registro.head(15))

print("\nConteo de decisiones finales:")
print(df_registro["decision_final"].value_counts())

print("\nConteo de acciones del AC:")
print(df_registro["estado_ac"].value_counts())


# ==========================================
# CÁLCULO DE IMPACTO ENERGÉTICO ESTIMADO
# ==========================================

total_lecturas = len(df_registro)

apagados = len(df_registro[df_registro["decision_final"] == "apagar"])
esperas = len(df_registro[df_registro["decision_final"] == "esperar_apagado"])
mantener = len(df_registro[df_registro["decision_final"] == "mantener"])
enfriar = len(df_registro[df_registro["decision_final"] == "enfriar_fuerte"])

porcentaje_apagado = apagados / total_lecturas
porcentaje_espera = esperas / total_lecturas
porcentaje_mantener = mantener / total_lecturas
porcentaje_enfriar = enfriar / total_lecturas

# Enfoque conservador:
# Solo se considera ahorro real cuando la decisión final es "apagar".
# "esperar_apagado" no se cuenta como ahorro porque el AC sigue encendido.
horas_ahorro_mes = horas_operacion_mes * porcentaje_apagado

kwh_sin_atmos = horas_operacion_mes * consumo_ac_kw * cantidad_aires
kwh_ahorrados = horas_ahorro_mes * consumo_ac_kw * cantidad_aires
kwh_con_atmos = kwh_sin_atmos - kwh_ahorrados

costo_sin_atmos = kwh_sin_atmos * tarifa_kwh
costo_con_atmos = kwh_con_atmos * tarifa_kwh

ahorro_mensual = kwh_ahorrados * tarifa_kwh
ahorro_anual = ahorro_mensual * 12

print("\n=== IMPACTO ESTIMADO BASADO EN DECISIONES DEL SISTEMA ===")
print(f"Lecturas simuladas: {total_lecturas}")
print(f"Decisiones finales de apagado: {apagados} ({porcentaje_apagado * 100:.1f}%)")
print(f"Decisiones de espera por temporizador: {esperas} ({porcentaje_espera * 100:.1f}%)")
print(f"Decisiones de mantener: {mantener} ({porcentaje_mantener * 100:.1f}%)")
print(f"Decisiones de enfriar fuerte: {enfriar} ({porcentaje_enfriar * 100:.1f}%)")
print()
print(f"Horas de operación estimadas al mes: {horas_operacion_mes:.2f} h")
print(f"Horas de AC ahorradas al mes: {horas_ahorro_mes:.2f} h")
print(f"Cantidad de aires considerados: {cantidad_aires}")
print(f"Consumo estimado por AC: {consumo_ac_kw} kW")
print(f"Tarifa eléctrica usada: B/. {tarifa_kwh} por kWh")
print()
print(f"Consumo mensual sin ATMOS: {kwh_sin_atmos:.2f} kWh")
print(f"Consumo mensual con ATMOS: {kwh_con_atmos:.2f} kWh")
print(f"Energía ahorrada al mes: {kwh_ahorrados:.2f} kWh")
print()
print(f"Costo mensual sin ATMOS: B/. {costo_sin_atmos:.2f}")
print(f"Costo mensual con ATMOS: B/. {costo_con_atmos:.2f}")
print(f"Ahorro mensual estimado: B/. {ahorro_mensual:.2f}")
print(f"Ahorro anual estimado por salón: B/. {ahorro_anual:.2f}")


# ==========================================
# GRÁFICAS DEL IMPACTO SIMULADO
# ==========================================

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Gráfica 1: distribución de decisiones finales
conteos = df_registro["decision_final"].value_counts()

colores = {
    "apagar": "#e74c3c",
    "esperar_apagado": "#95a5a6",
    "mantener": "#f39c12",
    "enfriar_fuerte": "#3498db"
}

ax1.bar(
    conteos.index,
    conteos.values,
    color=[colores.get(d, "#7f8c8d") for d in conteos.index]
)

ax1.set_title("Distribución de decisiones finales de ATMOS")
ax1.set_ylabel("Cantidad de lecturas")
ax1.set_xlabel("Decisión final")
ax1.tick_params(axis="x", rotation=20)

# Gráfica 2: consumo estimado
categorias = [
    "Sin ATMOS\n(AC encendido)",
    "Con ATMOS\n(control inteligente)"
]

kwh = [kwh_sin_atmos, kwh_con_atmos]

ax2.bar(categorias, kwh, color=["#e74c3c", "#2ecc71"])
ax2.set_title("Consumo energético mensual estimado")
ax2.set_ylabel("kWh consumidos")

for i, v in enumerate(kwh):
    ax2.text(i, v + 1, f"{v:.1f} kWh", ha="center", fontweight="bold")

plt.tight_layout()
plt.savefig("atmos_impacto_decisiones.png")
plt.show()

"""### 11.3 Impacto Real Basado en Datos Medidos

"""

print("=== IMPACTO REAL DE ATMOS CON DATOS MEDIDOS ===\n")

# Datos reales de mediciones
consumo_larso_mes = (897.2 + 1009.6) / 2      # promedio kWh
consumo_robotica_mes = (836.4 + 940.8) / 2
consumo_lai_mes = (745.2 + 838.4) / 2

# Porcentaje de tiempo vacío por salón
vacancia_larso = 29 / 95
vacancia_robotica = 24 / 95
vacancia_lai = 29 / 95  # ignoramos sábado

# Tarifa UTP (dato real del informe de desempeño energético)
tarifa = 0.22  # B/. por kWh estimado institucional

# Ahorro mensual por salón
ahorro_larso = consumo_larso_mes * vacancia_larso
ahorro_robotica = consumo_robotica_mes * vacancia_robotica
ahorro_lai = consumo_lai_mes * vacancia_lai
ahorro_total_mes = ahorro_larso + ahorro_robotica + ahorro_lai

print(f"LARSO    — Consumo mensual: {consumo_larso_mes:.1f} kWh | Vacío {vacancia_larso*100:.1f}% | Ahorro: {ahorro_larso:.1f} kWh")
print(f"Robótica — Consumo mensual: {consumo_robotica_mes:.1f} kWh | Vacío {vacancia_robotica*100:.1f}% | Ahorro: {ahorro_robotica:.1f} kWh")
print(f"LAI 1    — Consumo mensual: {consumo_lai_mes:.1f} kWh | Vacío {vacancia_lai*100:.1f}% | Ahorro: {ahorro_lai:.1f} kWh")
print(f"\nAhorro total mensual: {ahorro_total_mes:.1f} kWh = B/.{ahorro_total_mes * tarifa:.2f}")
print(f"Ahorro total anual:   {ahorro_total_mes * 10:.1f} kWh = B/.{ahorro_total_mes * tarifa * 10:.2f}")
print(f"(10 meses académicos)")

# Gráfica
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Gráfica 1: consumo vs ahorro por salón
salones = ['LARSO', 'Robótica', 'LAI 1']
consumos = [consumo_larso_mes, consumo_robotica_mes, consumo_lai_mes]
ahorros = [ahorro_larso, ahorro_robotica, ahorro_lai]
consumo_real = [c - a for c, a in zip(consumos, ahorros)]

x = range(len(salones))
width = 0.35

bars1 = axes[0].bar([i - width/2 for i in x], consumos, width,
                     label='Sin ATMOS', color='#e74c3c')
bars2 = axes[0].bar([i + width/2 for i in x], consumo_real, width,
                     label='Con ATMOS', color='#2ecc71')
axes[0].set_title('Consumo mensual por salón\n(datos reales medidos)')
axes[0].set_ylabel('kWh')
axes[0].set_xticks(x)
axes[0].set_xticklabels(salones)
axes[0].legend()

for bar in bars1:
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                f'{bar.get_height():.0f}', ha='center', fontsize=9)
for bar in bars2:
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                f'{bar.get_height():.0f}', ha='center', fontsize=9)

# Gráfica 2: ahorro anual total
categorias = ['Gasto anual\nSin ATMOS', 'Gasto anual\nCon ATMOS', 'Ahorro\nanual']
valores = [
    sum(consumos) * tarifa * 10,
    sum(consumo_real) * tarifa * 10,
    ahorro_total_mes * tarifa * 10
]
colores = ['#e74c3c', '#2ecc71', '#3498db']
bars = axes[1].bar(categorias, valores, color=colores)
axes[1].set_title('Impacto económico anual\n(3 salones, 10 meses académicos)')
axes[1].set_ylabel('Balboas (B/.)')
for bar in bars:
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
                f'B/.{bar.get_height():.2f}', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('atmos_impacto_real.png')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile atmos_logic.py
# 
# import pandas as pd
# 
# 
# # ==========================================
# # PARÁMETROS GENERALES DEL SISTEMA ATMOS
# # ==========================================
# 
# LIMITE_CALOR_MODERADO = 28
# LIMITE_CALOR_FUERTE = 30
# LIMITE_HUMEDAD_ALTA = 70
# DELTA_MINIMO_ESPERADO = 6
# TEMP_AC_POCO_FRIA = 22
# 
# TEMP_MANTENER = 24
# TEMP_ENFRIAR_MODERADO = 23
# TEMP_ENFRIAR_FUERTE = 22
# 
# TIEMPO_ESPERA_APAGADO = 10  # minutos
# 
# TIEMPO_MINIMO_FALLA = 30
# DESCENSO_MINIMO_ESPERADO = 3
# TEMP_AC_ALTA = 23
# 
# 
# # ==========================================
# # FUNCIÓN DE DECISIÓN BASE
# # ==========================================
# 
# def decidir(row):
#     if row["presencia"] == 0:
#         return "apagar"
# 
#     if row["temp_ambiente"] >= LIMITE_CALOR_FUERTE:
#         return "enfriar_fuerte"
# 
#     if row["temp_ambiente"] >= LIMITE_CALOR_MODERADO:
#         señales_calor = 0
# 
#         if row["humedad"] >= LIMITE_HUMEDAD_ALTA:
#             señales_calor += 1
# 
#         if row["delta_t"] < DELTA_MINIMO_ESPERADO:
#             señales_calor += 1
# 
#         if row["temp_ac"] >= TEMP_AC_POCO_FRIA:
#             señales_calor += 1
# 
#         if señales_calor >= 2:
#             return "enfriar_fuerte"
#         else:
#             return "mantener"
# 
#     return "mantener"
# 
# 
# # ==========================================
# # VALIDACIÓN DE ENTRADAS
# # ==========================================
# 
# def validar_lectura(presencia, temp_ambiente, temp_ac, humedad, minutos_sin_presencia=0):
#     errores = []
# 
#     if presencia not in [0, 1]:
#         errores.append("La variable 'presencia' debe ser 0 o 1.")
# 
#     if temp_ambiente < 10 or temp_ambiente > 45:
#         errores.append("La temperatura ambiente está fuera de un rango lógico (10°C a 45°C).")
# 
#     if temp_ac < 5 or temp_ac > 35:
#         errores.append("La temperatura del AC está fuera de un rango lógico (5°C a 35°C).")
# 
#     if humedad < 0 or humedad > 100:
#         errores.append("La humedad debe estar entre 0% y 100%.")
# 
#     if minutos_sin_presencia < 0:
#         errores.append("Los minutos sin presencia no pueden ser negativos.")
# 
#     return {
#         "valido": len(errores) == 0,
#         "errores": errores
#     }
# 
# 
# # ==========================================
# # PREDICCIÓN DE UNA LECTURA
# # ==========================================
# 
# def predecir_lectura(modelo, presencia, temp_ambiente, temp_ac, humedad):
#     delta_t = temp_ambiente - temp_ac
# 
#     lectura = pd.DataFrame([{
#         "presencia": presencia,
#         "temp_ambiente": temp_ambiente,
#         "temp_ac": temp_ac,
#         "delta_t": delta_t,
#         "humedad": humedad
#     }])
# 
#     decision_ml = modelo.predict(lectura)[0]
# 
#     return decision_ml, delta_t
# 
# 
# # ==========================================
# # CAPA DE SEGURIDAD
# # ==========================================
# 
# def aplicar_capa_seguridad(decision_ml, presencia, temp_ambiente, temp_ac, delta_t, humedad):
#     caso = pd.Series({
#         "presencia": presencia,
#         "temp_ambiente": temp_ambiente,
#         "temp_ac": temp_ac,
#         "delta_t": delta_t,
#         "humedad": humedad
#     })
# 
#     decision_regla = decidir(caso)
# 
#     if presencia == 0:
#         return decision_ml, "Sin presencia detectada. Se mantiene la decisión del modelo."
# 
#     if presencia == 1 and decision_ml == "apagar":
#         return "mantener", "Capa de seguridad: había presencia, se evita apagar el AC."
# 
#     if decision_ml == "enfriar_fuerte" and decision_regla == "mantener":
#         return "mantener", "Capa de seguridad: caso frontera. Se evita enfriar fuerte innecesariamente."
# 
#     return decision_ml, "La decisión del modelo fue aceptada por la capa de seguridad."
# 
# 
# # ==========================================
# # TEMPORIZADOR DE AUSENCIA
# # ==========================================
# 
# def aplicar_temporizador(decision_ml, presencia, minutos_sin_presencia):
#     if presencia == 0 and decision_ml == "apagar":
# 
#         if minutos_sin_presencia >= TIEMPO_ESPERA_APAGADO:
#             return "apagar"
# 
#         else:
#             return "esperar_apagado"
# 
#     return decision_ml
# 
# 
# # ==========================================
# # TRADUCCIÓN A ACCIÓN DEL AC
# # ==========================================
# 
# def traducir_decision_ac(decision_final, temp_ambiente):
#     if decision_final == "apagar":
#         return {
#             "estado_ac": "apagado",
#             "temperatura_objetivo": None,
#             "modo": "off",
#             "ventilacion": "apagada",
#             "accion": "Enviar comando IR para apagar el aire acondicionado"
#         }
# 
#     elif decision_final == "esperar_apagado":
#         return {
#             "estado_ac": "encendido",
#             "temperatura_objetivo": "sin cambio",
#             "modo": "sin cambio",
#             "ventilacion": "sin cambio",
#             "accion": "No enviar nuevo comando. Esperar hasta cumplir los 10 minutos sin presencia"
#         }
# 
#     elif decision_final == "mantener":
#         return {
#             "estado_ac": "encendido",
#             "temperatura_objetivo": TEMP_MANTENER,
#             "modo": "cool",
#             "ventilacion": "automatica",
#             "accion": f"Mantener el aire acondicionado en {TEMP_MANTENER}°C"
#         }
# 
#     elif decision_final == "enfriar_fuerte":
# 
#         if temp_ambiente >= LIMITE_CALOR_FUERTE:
#             temperatura = TEMP_ENFRIAR_FUERTE
#             ventilacion = "alta"
#         else:
#             temperatura = TEMP_ENFRIAR_MODERADO
#             ventilacion = "media"
# 
#         return {
#             "estado_ac": "encendido",
#             "temperatura_objetivo": temperatura,
#             "modo": "cool",
#             "ventilacion": ventilacion,
#             "accion": f"Configurar el aire a {temperatura}°C con ventilación {ventilacion}"
#         }
# 
#     return {
#         "estado_ac": "desconocido",
#         "temperatura_objetivo": None,
#         "modo": "desconocido",
#         "ventilacion": "desconocida",
#         "accion": "Decisión no reconocida"
#     }
# 
# 
# # ==========================================
# # DETECCIÓN DE FALLAS
# # ==========================================
# 
# def detectar_falla_ac(decision_final, minutos_enfriando, temp_inicio, temp_actual, temp_ac_actual):
#     if decision_final != "enfriar_fuerte":
#         return {
#             "estado_falla": "no_aplica",
#             "alerta": False,
#             "mensaje": "No se evalúa falla porque el sistema no está en modo enfriar_fuerte."
#         }
# 
#     if minutos_enfriando < TIEMPO_MINIMO_FALLA:
#         return {
#             "estado_falla": "monitoreando",
#             "alerta": False,
#             "mensaje": f"El sistema lleva {minutos_enfriando} minutos enfriando. Aún no se evalúa falla."
#         }
# 
#     descenso_temp = temp_inicio - temp_actual
# 
#     if descenso_temp < DESCENSO_MINIMO_ESPERADO:
#         if temp_ac_actual >= TEMP_AC_ALTA:
#             mensaje = (
#                 f"Posible falla del AC: después de {minutos_enfriando} minutos en enfriar_fuerte, "
#                 f"la temperatura solo bajó {descenso_temp:.1f}°C y el aire del AC sale a {temp_ac_actual}°C."
#             )
#         else:
#             mensaje = (
#                 f"Posible bajo rendimiento: después de {minutos_enfriando} minutos en enfriar_fuerte, "
#                 f"la temperatura solo bajó {descenso_temp:.1f}°C."
#             )
# 
#         return {
#             "estado_falla": "posible_falla",
#             "alerta": True,
#             "descenso_temperatura": round(descenso_temp, 2),
#             "mensaje": mensaje
#         }
# 
#     return {
#         "estado_falla": "funcionamiento_normal",
#         "alerta": False,
#         "descenso_temperatura": round(descenso_temp, 2),
#         "mensaje": f"El AC funciona correctamente. La temperatura bajó {descenso_temp:.1f}°C."
#     }
# 
# 
# # ==========================================
# # FUNCIÓN PRINCIPAL DEL SISTEMA ATMOS
# # ==========================================
# 
# def ejecutar_atmos(
#     modelo,
#     presencia,
#     temp_ambiente,
#     temp_ac,
#     humedad,
#     minutos_sin_presencia=0,
#     minutos_enfriando=0,
#     temp_inicio=None,
#     temp_actual=None,
#     temp_ac_actual=None,
#     usar_capa_seguridad=True
# ):
#     validacion = validar_lectura(
#         presencia,
#         temp_ambiente,
#         temp_ac,
#         humedad,
#         minutos_sin_presencia
#     )
# 
#     if not validacion["valido"]:
#         return {
#             "valido": False,
#             "errores": validacion["errores"],
#             "mensaje": "La lectura no pudo procesarse porque contiene datos inválidos."
#         }
# 
#     decision_ml, delta_t = predecir_lectura(
#         modelo,
#         presencia,
#         temp_ambiente,
#         temp_ac,
#         humedad
#     )
# 
#     lectura_prob = pd.DataFrame([{
#         "presencia": presencia,
#         "temp_ambiente": temp_ambiente,
#         "temp_ac": temp_ac,
#         "delta_t": delta_t,
#         "humedad": humedad
#     }])
# 
#     probabilidades_array = modelo.predict_proba(lectura_prob)[0]
# 
#     probabilidades = {
#         clase: float(round(prob * 100, 2))
#         for clase, prob in zip(modelo.classes_, probabilidades_array)
#     }
# 
#     if usar_capa_seguridad:
#         decision_segura, mensaje_seguridad = aplicar_capa_seguridad(
#             decision_ml,
#             presencia,
#             temp_ambiente,
#             temp_ac,
#             delta_t,
#             humedad
#         )
#     else:
#         decision_segura = decision_ml
#         mensaje_seguridad = "Capa de seguridad desactivada."
# 
#     decision_final = aplicar_temporizador(
#         decision_segura,
#         presencia,
#         minutos_sin_presencia
#     )
# 
#     accion_ac = traducir_decision_ac(
#         decision_final,
#         temp_ambiente
#     )
# 
#     if temp_inicio is not None and temp_actual is not None and temp_ac_actual is not None:
#         falla_ac = detectar_falla_ac(
#             decision_final,
#             minutos_enfriando,
#             temp_inicio,
#             temp_actual,
#             temp_ac_actual
#         )
#     else:
#         falla_ac = {
#             "estado_falla": "no_evaluada",
#             "alerta": False,
#             "mensaje": "No se evaluó falla porque no se proporcionaron datos históricos de enfriamiento."
#         }
# 
#     return {
#         "valido": True,
#         "lectura": {
#             "presencia": presencia,
#             "temp_ambiente": temp_ambiente,
#             "temp_ac": temp_ac,
#             "delta_t": round(delta_t, 2),
#             "humedad": humedad,
#             "minutos_sin_presencia": minutos_sin_presencia
#         },
#         "modelo": {
#             "decision_ml": decision_ml,
#             "probabilidades": probabilidades
#         },
#         "seguridad": {
#             "decision_segura": decision_segura,
#             "mensaje": mensaje_seguridad
#         },
#         "control": {
#             "decision_final": decision_final,
#             "accion_ac": accion_ac
#         },
#         "deteccion_fallas": falla_ac
#     }